name: "autobuild"
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'    # At 1AM UTC Every day

jobs:
  singleJobName:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
       
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.WORKFLOWS_TOKEN }}
        repository: ${{ github.repository }}/alpine-nginx-php
        push: true
        tag_with_sha: true
        tag_with_ref: true
        tags: latest
